version: 0.0
os: linux

files:
  - source: target/case-yellow-analysis.jar
    destination: /home/ec2-user/case-yellow

hooks:
  ApplicationStop:
    - location: scripts/upload_metabasedb_files.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/delete_app_binary.sh
      timeout: 60
      runas: ec2-user

    - location: scripts/download_metabasedb_files.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/stop_app_process.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_app_process.sh
      timeout: 120
      runas: ec2-user