# Server Port
server.port : 7008

# Profiles
spring.profiles.active: prod

# Google Vision Service
google_vision_url : https://vision.googleapis.com/

central_url: http://localhost:9080

# MultiPart properties
spring.http.multipart.max-file-size: 5MB
spring.http.multipart.max-request-size: 20MB

# Identifiers Meta Data
hot_location: Mbps
hot_identifier: Mbps
hot_identifier_count: 2

bezeq_Mb_location: Mb/s
bezeq_Kb_location: Kb/s

ookla_identifier: Mbps
ookla_identifier_count: 2

imgParsersIdentifiers:
 hot: hotImageParser
 ookla: ooklaImageParser
 bezeq: bezeqImageParser

# Logger
log.dir: /home/ec2-user/case-yellow-analysis

logging:
 level:
   org.springframework.web: ERROR
   caseyellow.server.gateway: INFO
   org.hibernate: INFO
 pattern:
   console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - %m%n"
   file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - %m%n"
 file: ${log.dir}/logs/case_yellow_analysis_log.log